
openapi: 3.0.0
info:
  title: Gateway API
  description: A gateway for managing differnt APIs
  version: 1.0.0
servers:
  - url: http://127.0.0.1:9000
    description: The API server
paths:
  /ws:
    get:
      summary: Receive events via WebSocket
      responses:
        '200':
          description: Successfully connected to the WebSocket
      servers:
        - url: ws://example.com/ws
components:
  schemas:
    WsEvent:
      type: object
      properties:
        content:
          type: string
        type:
          type: string