openapi: 3.0.0
info:
  title: Gateway API
  description: A gateway for managing different APIs
  version: 1.0.0
servers:
  - url: https://gateway.sekyr.com
    description: The production API server
  - url: http://127.0.0.1:9000
    description: The local API server for development
tags:
  - name: WebSocket
    description: WebSocket API
paths:
  /ws:
    get:
      summary: Receive events via WebSocket
      description: Use this endpoint to establish a WebSocket connection and receive events.
      responses:
        '200':
          description: Successfully connected to the WebSocket.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WsEvent'
      servers:
        - url: ws://127.0.0.1:9000/ws
      x-websocket: true
      tags:
        - WebSocket
components:
  schemas:
    WsEvent:
      type: object
      description: A WebSocket event.
      properties:
        content:
          type: string
        type:
          oneOf:
            - $ref: '#/components/schemas/BeaconCreated'
            - $ref: '#/components/schemas/EventCreated'
            - $ref: '#/components/schemas/RecipientError'
    BeaconCreated:
      type: object
      description: A beacon was created.
      properties:
        BeaconId:
          type: string
          format: uuid
        GroupId:
          type: string
          format: uuid
      required:
        - BeaconId
        - GroupId
    EventCreated:
      type: object
      description: An event was created by a beacon.
      properties:
        EventId:
          type: string
          format: uuid
        BeaconId:
          type: string
          format: uuid
        BinaryName:
          type: string
        Arguments:
          type: string
        Host:
          type: string
      required:
        - EventId
        - BeaconId
        - BinaryName
    RecipientError:
      type: object
      description: An error occurred while sending an event to a recipient.
      properties:
        RecipientErrorId:
          type: string
          format: uuid
        RecipientId:
          type: string
          format: uuid
        Error:
          type: string
      required:
        - RecipientErrorId
        - RecipientId
        - Error
